name: LOCAL
keycloak:
  host: http://localhost:9000
  realm-admin: master
  user: furialfonso
  pass: Admin123
  realm: test
  client: cow
cow-api:
  url: http://localhost:8080
  timeout: 5s
eureka:
  url: http://localhost:8761/eureka
  timeout: 5s