name: LOCAL
keycloak:
  host: http://localhost:9001
  realm-admin: admin-cli
  user: furialfonso
  pass: Admin123
  realm: Test
  client: cow
cow-api:
  url: http://localhost:8080
  timeout: 5s