name: PRODUCTION
keycloak:
  host: http://keycloak:8080/auth
  realm-admin: master
  user: furialfonso
  pass: Admin123
  realm: Production
  client: cow
cow-api:
  url: http://localhost:7070
  timeout: 5s