name: PRODUCTION
keycloak:
  host: http://keycloak_prod:8080
  realm-admin: master
  user: furialfonso
  pass: Admin123
  realm: master
  client: cow
cow-api:
  url: http://localhost:7070
  timeout: 5s
eureka:
  url: http://eureka-service:8761/eureka
  interval: 10
  duration: 30